# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Mon Feb 01 18:23:34 2016
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1155, 986)
        self.centralwidget = QtGui.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1133, 962))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.groupBox_parameter = QtGui.QGroupBox(self.tab_1)
        self.groupBox_parameter.setGeometry(QtCore.QRect(20, 10, 191, 901))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_parameter.setFont(font)
        self.groupBox_parameter.setObjectName(_fromUtf8("groupBox_parameter"))
        self.label_starting_value = QtGui.QLabel(self.groupBox_parameter)
        self.label_starting_value.setGeometry(QtCore.QRect(10, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_starting_value.setFont(font)
        self.label_starting_value.setObjectName(_fromUtf8("label_starting_value"))
        self.lineEdit_start = QtGui.QLineEdit(self.groupBox_parameter)
        self.lineEdit_start.setGeometry(QtCore.QRect(10, 50, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_start.setFont(font)
        self.lineEdit_start.setObjectName(_fromUtf8("lineEdit_start"))
        self.pushButton_plot = QtGui.QPushButton(self.groupBox_parameter)
        self.pushButton_plot.setGeometry(QtCore.QRect(60, 690, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_plot.setFont(font)
        self.pushButton_plot.setObjectName(_fromUtf8("pushButton_plot"))
        self.pushButton_clear = QtGui.QPushButton(self.groupBox_parameter)
        self.pushButton_clear.setEnabled(False)
        self.pushButton_clear.setGeometry(QtCore.QRect(60, 740, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName(_fromUtf8("pushButton_clear"))
        self.textEdit_peaks_steps = QtGui.QTextEdit(self.groupBox_parameter)
        self.textEdit_peaks_steps.setGeometry(QtCore.QRect(10, 120, 171, 551))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit_peaks_steps.setFont(font)
        self.textEdit_peaks_steps.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_peaks_steps.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_peaks_steps.setTabStopWidth(80)
        self.textEdit_peaks_steps.setCursorWidth(2)
        self.textEdit_peaks_steps.setObjectName(_fromUtf8("textEdit_peaks_steps"))
        self.label_2 = QtGui.QLabel(self.groupBox_parameter)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.groupBox_save_general = QtGui.QGroupBox(self.tab_1)
        self.groupBox_save_general.setGeometry(QtCore.QRect(230, 10, 541, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_save_general.setFont(font)
        self.groupBox_save_general.setObjectName(_fromUtf8("groupBox_save_general"))
        self.lineEdit_array_name = QtGui.QLineEdit(self.groupBox_save_general)
        self.lineEdit_array_name.setGeometry(QtCore.QRect(20, 50, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_array_name.setFont(font)
        self.lineEdit_array_name.setObjectName(_fromUtf8("lineEdit_array_name"))
        self.label_4 = QtGui.QLabel(self.groupBox_save_general)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pushButton_save = QtGui.QPushButton(self.groupBox_save_general)
        self.pushButton_save.setEnabled(False)
        self.pushButton_save.setGeometry(QtCore.QRect(440, 70, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.label_6 = QtGui.QLabel(self.groupBox_save_general)
        self.label_6.setGeometry(QtCore.QRect(20, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_directory_save = QtGui.QLineEdit(self.groupBox_save_general)
        self.lineEdit_directory_save.setGeometry(QtCore.QRect(20, 110, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_directory_save.setFont(font)
        self.lineEdit_directory_save.setObjectName(_fromUtf8("lineEdit_directory_save"))
        self.pushButton_browse_save = QtGui.QPushButton(self.groupBox_save_general)
        self.pushButton_browse_save.setGeometry(QtCore.QRect(440, 30, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_browse_save.setFont(font)
        self.pushButton_browse_save.setObjectName(_fromUtf8("pushButton_browse_save"))
        self.label_10 = QtGui.QLabel(self.groupBox_save_general)
        self.label_10.setGeometry(QtCore.QRect(230, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_user_name = QtGui.QLineEdit(self.groupBox_save_general)
        self.lineEdit_user_name.setGeometry(QtCore.QRect(230, 50, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_user_name.setFont(font)
        self.lineEdit_user_name.setObjectName(_fromUtf8("lineEdit_user_name"))
        self.groupBox_plot = QtGui.QGroupBox(self.tab_1)
        self.groupBox_plot.setGeometry(QtCore.QRect(230, 170, 861, 741))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_plot.setFont(font)
        self.groupBox_plot.setObjectName(_fromUtf8("groupBox_plot"))
        self.mplwidget_general = MatplotlibWidget(self.groupBox_plot)
        self.mplwidget_general.setGeometry(QtCore.QRect(350, 270, 16, 16))
        self.mplwidget_general.setObjectName(_fromUtf8("mplwidget_general"))
        self.widget_general = QtGui.QWidget(self.groupBox_plot)
        self.widget_general.setGeometry(QtCore.QRect(0, 10, 861, 731))
        self.widget_general.setObjectName(_fromUtf8("widget_general"))
        self.groupBox_condition_general = QtGui.QGroupBox(self.tab_1)
        self.groupBox_condition_general.setGeometry(QtCore.QRect(790, 10, 301, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_condition_general.setFont(font)
        self.groupBox_condition_general.setObjectName(_fromUtf8("groupBox_condition_general"))
        self.textEdit_condition = QtGui.QTextEdit(self.groupBox_condition_general)
        self.textEdit_condition.setGeometry(QtCore.QRect(20, 50, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEdit_condition.setFont(font)
        self.textEdit_condition.setObjectName(_fromUtf8("textEdit_condition"))
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_import_keithley = QtGui.QGroupBox(self.tab_2)
        self.groupBox_import_keithley.setGeometry(QtCore.QRect(10, 10, 311, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_import_keithley.setFont(font)
        self.groupBox_import_keithley.setObjectName(_fromUtf8("groupBox_import_keithley"))
        self.lineEdit_directory_keithley = QtGui.QLineEdit(self.groupBox_import_keithley)
        self.lineEdit_directory_keithley.setGeometry(QtCore.QRect(10, 50, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_directory_keithley.setFont(font)
        self.lineEdit_directory_keithley.setObjectName(_fromUtf8("lineEdit_directory_keithley"))
        self.label_7 = QtGui.QLabel(self.groupBox_import_keithley)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pushButton_browse_keithley = QtGui.QPushButton(self.groupBox_import_keithley)
        self.pushButton_browse_keithley.setGeometry(QtCore.QRect(10, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_browse_keithley.setFont(font)
        self.pushButton_browse_keithley.setObjectName(_fromUtf8("pushButton_browse_keithley"))
        self.pushButton_import_keithley = QtGui.QPushButton(self.groupBox_import_keithley)
        self.pushButton_import_keithley.setEnabled(False)
        self.pushButton_import_keithley.setGeometry(QtCore.QRect(120, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_import_keithley.setFont(font)
        self.pushButton_import_keithley.setObjectName(_fromUtf8("pushButton_import_keithley"))
        self.pushButton_copy_keithley = QtGui.QPushButton(self.groupBox_import_keithley)
        self.pushButton_copy_keithley.setEnabled(True)
        self.pushButton_copy_keithley.setGeometry(QtCore.QRect(230, 100, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_copy_keithley.setFont(font)
        self.pushButton_copy_keithley.setObjectName(_fromUtf8("pushButton_copy_keithley"))
        self.tabWidget_plot_keithely = QtGui.QTabWidget(self.tab_2)
        self.tabWidget_plot_keithely.setEnabled(True)
        self.tabWidget_plot_keithely.setGeometry(QtCore.QRect(10, 230, 1081, 681))
        self.tabWidget_plot_keithely.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget_plot_keithely.setObjectName(_fromUtf8("tabWidget_plot_keithely"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.widget_import = QtGui.QWidget(self.tab_3)
        self.widget_import.setGeometry(QtCore.QRect(0, 0, 1081, 651))
        self.widget_import.setObjectName(_fromUtf8("widget_import"))
        self.mplwidget_import = MatplotlibWidget(self.widget_import)
        self.mplwidget_import.setGeometry(QtCore.QRect(520, 230, 16, 16))
        self.mplwidget_import.setObjectName(_fromUtf8("mplwidget_import"))
        self.tabWidget_plot_keithely.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scrollArea_2 = QtGui.QScrollArea(self.tab_4)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.scrollArea_2.setBaseSize(QtCore.QSize(0, 0))
        self.scrollArea_2.setWidgetResizable(False)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -5, 1019, 1409))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.curvewidget_ct_keithley = CurveWidget(self.scrollAreaWidgetContents_2)
        self.curvewidget_ct_keithley.setGeometry(QtCore.QRect(20, 10, 991, 311))
        self.curvewidget_ct_keithley.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_ct_keithley.setObjectName(_fromUtf8("curvewidget_ct_keithley"))
        self.curvewidget_vt_keithley = CurveWidget(self.scrollAreaWidgetContents_2)
        self.curvewidget_vt_keithley.setGeometry(QtCore.QRect(20, 340, 991, 311))
        self.curvewidget_vt_keithley.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_vt_keithley.setObjectName(_fromUtf8("curvewidget_vt_keithley"))
        self.curvewidget_keithley = CurveWidget(self.scrollAreaWidgetContents_2)
        self.curvewidget_keithley.setGeometry(QtCore.QRect(20, 710, 991, 591))
        self.curvewidget_keithley.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_keithley.setObjectName(_fromUtf8("curvewidget_keithley"))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.addWidget(self.scrollArea_2, 1, 0, 1, 1)
        self.tabWidget_plot_keithely.addTab(self.tab_4, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.widget_analysis = QtGui.QWidget(self.tab_6)
        self.widget_analysis.setGeometry(QtCore.QRect(0, 0, 1081, 651))
        self.widget_analysis.setObjectName(_fromUtf8("widget_analysis"))
        self.mplwidget_analysis = MatplotlibWidget(self.widget_analysis)
        self.mplwidget_analysis.setGeometry(QtCore.QRect(520, 230, 16, 16))
        self.mplwidget_analysis.setObjectName(_fromUtf8("mplwidget_analysis"))
        self.tabWidget_plot_keithely.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.groupBox_save_keithley = QtGui.QGroupBox(self.tab_7)
        self.groupBox_save_keithley.setEnabled(False)
        self.groupBox_save_keithley.setGeometry(QtCore.QRect(140, 60, 811, 481))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_save_keithley.setFont(font)
        self.groupBox_save_keithley.setObjectName(_fromUtf8("groupBox_save_keithley"))
        self.label_21 = QtGui.QLabel(self.groupBox_save_keithley)
        self.label_21.setGeometry(QtCore.QRect(60, 40, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lineEdit_GoogleDrive_keithley = QtGui.QLineEdit(self.groupBox_save_keithley)
        self.lineEdit_GoogleDrive_keithley.setGeometry(QtCore.QRect(60, 70, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_GoogleDrive_keithley.setFont(font)
        self.lineEdit_GoogleDrive_keithley.setObjectName(_fromUtf8("lineEdit_GoogleDrive_keithley"))
        self.label_22 = QtGui.QLabel(self.groupBox_save_keithley)
        self.label_22.setEnabled(False)
        self.label_22.setGeometry(QtCore.QRect(60, 170, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.comboBox_Name_Folder_keithley = QtGui.QComboBox(self.groupBox_save_keithley)
        self.comboBox_Name_Folder_keithley.setEnabled(False)
        self.comboBox_Name_Folder_keithley.setGeometry(QtCore.QRect(60, 200, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_Name_Folder_keithley.setFont(font)
        self.comboBox_Name_Folder_keithley.setObjectName(_fromUtf8("comboBox_Name_Folder_keithley"))
        self.comboBox_Name_Folder_keithley.addItem(_fromUtf8(""))
        self.comboBox_Name_Folder_keithley.addItem(_fromUtf8(""))
        self.comboBox_Name_Folder_keithley.addItem(_fromUtf8(""))
        self.comboBox_Name_Folder_keithley.addItem(_fromUtf8(""))
        self.comboBox_Name_Folder_keithley.addItem(_fromUtf8(""))
        self.comboBox_Name_Folder_keithley.addItem(_fromUtf8(""))
        self.comboBox_Name_Folder_keithley.addItem(_fromUtf8(""))
        self.comboBox_Name_Folder_keithley.addItem(_fromUtf8(""))
        self.pushButton_Select_Directory_keithley = QtGui.QPushButton(self.groupBox_save_keithley)
        self.pushButton_Select_Directory_keithley.setEnabled(False)
        self.pushButton_Select_Directory_keithley.setGeometry(QtCore.QRect(260, 200, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Select_Directory_keithley.setFont(font)
        self.pushButton_Select_Directory_keithley.setObjectName(_fromUtf8("pushButton_Select_Directory_keithley"))
        self.groupBox_File_Type_keithley = QtGui.QGroupBox(self.groupBox_save_keithley)
        self.groupBox_File_Type_keithley.setEnabled(False)
        self.groupBox_File_Type_keithley.setGeometry(QtCore.QRect(60, 260, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_File_Type_keithley.setFont(font)
        self.groupBox_File_Type_keithley.setObjectName(_fromUtf8("groupBox_File_Type_keithley"))
        self.radioButton_csv_keithley = QtGui.QRadioButton(self.groupBox_File_Type_keithley)
        self.radioButton_csv_keithley.setGeometry(QtCore.QRect(40, 20, 61, 31))
        self.radioButton_csv_keithley.setAcceptDrops(False)
        self.radioButton_csv_keithley.setAutoFillBackground(False)
        self.radioButton_csv_keithley.setChecked(True)
        self.radioButton_csv_keithley.setObjectName(_fromUtf8("radioButton_csv_keithley"))
        self.radioButton_txt_keithley = QtGui.QRadioButton(self.groupBox_File_Type_keithley)
        self.radioButton_txt_keithley.setGeometry(QtCore.QRect(140, 20, 61, 31))
        self.radioButton_txt_keithley.setObjectName(_fromUtf8("radioButton_txt_keithley"))
        self.groupBox_Filename_keithley = QtGui.QGroupBox(self.groupBox_save_keithley)
        self.groupBox_Filename_keithley.setEnabled(False)
        self.groupBox_Filename_keithley.setGeometry(QtCore.QRect(410, 40, 341, 151))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_Filename_keithley.setFont(font)
        self.groupBox_Filename_keithley.setObjectName(_fromUtf8("groupBox_Filename_keithley"))
        self.radioButton_Timename_keithley = QtGui.QRadioButton(self.groupBox_Filename_keithley)
        self.radioButton_Timename_keithley.setGeometry(QtCore.QRect(20, 30, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_Timename_keithley.setFont(font)
        self.radioButton_Timename_keithley.setChecked(True)
        self.radioButton_Timename_keithley.setObjectName(_fromUtf8("radioButton_Timename_keithley"))
        self.radioButton_Custom_Name_keithley = QtGui.QRadioButton(self.groupBox_Filename_keithley)
        self.radioButton_Custom_Name_keithley.setGeometry(QtCore.QRect(20, 70, 121, 21))
        self.radioButton_Custom_Name_keithley.setObjectName(_fromUtf8("radioButton_Custom_Name_keithley"))
        self.lineEdit_Custom_Name_keithley = QtGui.QLineEdit(self.groupBox_Filename_keithley)
        self.lineEdit_Custom_Name_keithley.setEnabled(False)
        self.lineEdit_Custom_Name_keithley.setGeometry(QtCore.QRect(40, 100, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Custom_Name_keithley.setFont(font)
        self.lineEdit_Custom_Name_keithley.setObjectName(_fromUtf8("lineEdit_Custom_Name_keithley"))
        self.pushButton_Save_keithley = QtGui.QPushButton(self.groupBox_save_keithley)
        self.pushButton_Save_keithley.setEnabled(False)
        self.pushButton_Save_keithley.setGeometry(QtCore.QRect(520, 380, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Save_keithley.setFont(font)
        self.pushButton_Save_keithley.setObjectName(_fromUtf8("pushButton_Save_keithley"))
        self.pushButton_Open_keithley = QtGui.QPushButton(self.groupBox_save_keithley)
        self.pushButton_Open_keithley.setEnabled(False)
        self.pushButton_Open_keithley.setGeometry(QtCore.QRect(650, 380, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Open_keithley.setFont(font)
        self.pushButton_Open_keithley.setObjectName(_fromUtf8("pushButton_Open_keithley"))
        self.pushButton_browse_save_keithley = QtGui.QPushButton(self.groupBox_save_keithley)
        self.pushButton_browse_save_keithley.setGeometry(QtCore.QRect(100, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_browse_save_keithley.setFont(font)
        self.pushButton_browse_save_keithley.setObjectName(_fromUtf8("pushButton_browse_save_keithley"))
        self.pushButton_check_keithley = QtGui.QPushButton(self.groupBox_save_keithley)
        self.pushButton_check_keithley.setGeometry(QtCore.QRect(220, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_check_keithley.setFont(font)
        self.pushButton_check_keithley.setObjectName(_fromUtf8("pushButton_check_keithley"))
        self.label_15 = QtGui.QLabel(self.groupBox_save_keithley)
        self.label_15.setGeometry(QtCore.QRect(60, 360, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lineEdit_save_condition_keithley = QtGui.QLineEdit(self.groupBox_save_keithley)
        self.lineEdit_save_condition_keithley.setGeometry(QtCore.QRect(60, 390, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_save_condition_keithley.setFont(font)
        self.lineEdit_save_condition_keithley.setObjectName(_fromUtf8("lineEdit_save_condition_keithley"))
        self.textEdit_comment_keithley = QtGui.QTextEdit(self.groupBox_save_keithley)
        self.textEdit_comment_keithley.setEnabled(False)
        self.textEdit_comment_keithley.setGeometry(QtCore.QRect(410, 240, 341, 111))
        self.textEdit_comment_keithley.setObjectName(_fromUtf8("textEdit_comment_keithley"))
        self.label_32 = QtGui.QLabel(self.groupBox_save_keithley)
        self.label_32.setEnabled(False)
        self.label_32.setGeometry(QtCore.QRect(410, 210, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.tabWidget_plot_keithely.addTab(self.tab_7, _fromUtf8(""))
        self.groupBox_condition_keithley = QtGui.QGroupBox(self.tab_2)
        self.groupBox_condition_keithley.setGeometry(QtCore.QRect(10, 150, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_condition_keithley.setFont(font)
        self.groupBox_condition_keithley.setObjectName(_fromUtf8("groupBox_condition_keithley"))
        self.lineEdit_condition_keithley = QtGui.QLineEdit(self.groupBox_condition_keithley)
        self.lineEdit_condition_keithley.setGeometry(QtCore.QRect(10, 30, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_condition_keithley.setFont(font)
        self.lineEdit_condition_keithley.setObjectName(_fromUtf8("lineEdit_condition_keithley"))
        self.groupBox_visa_keithley = QtGui.QGroupBox(self.tab_2)
        self.groupBox_visa_keithley.setEnabled(False)
        self.groupBox_visa_keithley.setGeometry(QtCore.QRect(330, 10, 321, 211))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_visa_keithley.setFont(font)
        self.groupBox_visa_keithley.setObjectName(_fromUtf8("groupBox_visa_keithley"))
        self.label_chooseVisa = QtGui.QLabel(self.groupBox_visa_keithley)
        self.label_chooseVisa.setGeometry(QtCore.QRect(20, 20, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa.setFont(font)
        self.label_chooseVisa.setObjectName(_fromUtf8("label_chooseVisa"))
        self.comboBox_visa_keithley = QtGui.QComboBox(self.groupBox_visa_keithley)
        self.comboBox_visa_keithley.setGeometry(QtCore.QRect(10, 50, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_visa_keithley.setFont(font)
        self.comboBox_visa_keithley.setObjectName(_fromUtf8("comboBox_visa_keithley"))
        self.pushButton_select_keithley = QtGui.QPushButton(self.groupBox_visa_keithley)
        self.pushButton_select_keithley.setGeometry(QtCore.QRect(60, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_keithley.setFont(font)
        self.pushButton_select_keithley.setObjectName(_fromUtf8("pushButton_select_keithley"))
        self.pushButton_close_keithley = QtGui.QPushButton(self.groupBox_visa_keithley)
        self.pushButton_close_keithley.setGeometry(QtCore.QRect(190, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_keithley.setFont(font)
        self.pushButton_close_keithley.setObjectName(_fromUtf8("pushButton_close_keithley"))
        self.label_8 = QtGui.QLabel(self.groupBox_visa_keithley)
        self.label_8.setGeometry(QtCore.QRect(20, 140, 311, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_visa_keithley = QtGui.QLineEdit(self.groupBox_visa_keithley)
        self.lineEdit_visa_keithley.setGeometry(QtCore.QRect(10, 170, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_visa_keithley.setFont(font)
        self.lineEdit_visa_keithley.setObjectName(_fromUtf8("lineEdit_visa_keithley"))
        self.groupBox_scan_keithley = QtGui.QGroupBox(self.tab_2)
        self.groupBox_scan_keithley.setEnabled(False)
        self.groupBox_scan_keithley.setGeometry(QtCore.QRect(660, 10, 431, 211))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_scan_keithley.setFont(font)
        self.groupBox_scan_keithley.setObjectName(_fromUtf8("groupBox_scan_keithley"))
        self.label = QtGui.QLabel(self.groupBox_scan_keithley)
        self.label.setGeometry(QtCore.QRect(10, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.radioButton_voltage_keithley = QtGui.QRadioButton(self.groupBox_scan_keithley)
        self.radioButton_voltage_keithley.setGeometry(QtCore.QRect(70, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_voltage_keithley.setFont(font)
        self.radioButton_voltage_keithley.setChecked(True)
        self.radioButton_voltage_keithley.setObjectName(_fromUtf8("radioButton_voltage_keithley"))
        self.pushButton_scan_keithley = QtGui.QPushButton(self.groupBox_scan_keithley)
        self.pushButton_scan_keithley.setGeometry(QtCore.QRect(170, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_scan_keithley.setFont(font)
        self.pushButton_scan_keithley.setObjectName(_fromUtf8("pushButton_scan_keithley"))
        self.pushButton_stop_keithley = QtGui.QPushButton(self.groupBox_scan_keithley)
        self.pushButton_stop_keithley.setEnabled(False)
        self.pushButton_stop_keithley.setGeometry(QtCore.QRect(290, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_stop_keithley.setFont(font)
        self.pushButton_stop_keithley.setObjectName(_fromUtf8("pushButton_stop_keithley"))
        self.pushButton_clear_keithley = QtGui.QPushButton(self.groupBox_scan_keithley)
        self.pushButton_clear_keithley.setEnabled(False)
        self.pushButton_clear_keithley.setGeometry(QtCore.QRect(340, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_clear_keithley.setFont(font)
        self.pushButton_clear_keithley.setObjectName(_fromUtf8("pushButton_clear_keithley"))
        self.label_xname_keithley = QtGui.QLabel(self.groupBox_scan_keithley)
        self.label_xname_keithley.setGeometry(QtCore.QRect(210, 50, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_xname_keithley.setFont(font)
        self.label_xname_keithley.setObjectName(_fromUtf8("label_xname_keithley"))
        self.label_yname_keithley = QtGui.QLabel(self.groupBox_scan_keithley)
        self.label_yname_keithley.setGeometry(QtCore.QRect(210, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_yname_keithley.setFont(font)
        self.label_yname_keithley.setObjectName(_fromUtf8("label_yname_keithley"))
        self.pushButton_pause_keithley = QtGui.QPushButton(self.groupBox_scan_keithley)
        self.pushButton_pause_keithley.setEnabled(False)
        self.pushButton_pause_keithley.setGeometry(QtCore.QRect(220, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_pause_keithley.setFont(font)
        self.pushButton_pause_keithley.setObjectName(_fromUtf8("pushButton_pause_keithley"))
        self.label_yunit_keithley = QtGui.QLabel(self.groupBox_scan_keithley)
        self.label_yunit_keithley.setGeometry(QtCore.QRect(350, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_yunit_keithley.setFont(font)
        self.label_yunit_keithley.setText(_fromUtf8(""))
        self.label_yunit_keithley.setObjectName(_fromUtf8("label_yunit_keithley"))
        self.label_xunit_keithley = QtGui.QLabel(self.groupBox_scan_keithley)
        self.label_xunit_keithley.setGeometry(QtCore.QRect(350, 50, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_xunit_keithley.setFont(font)
        self.label_xunit_keithley.setText(_fromUtf8(""))
        self.label_xunit_keithley.setObjectName(_fromUtf8("label_xunit_keithley"))
        self.tabWidget_scan_keithley = QtGui.QTabWidget(self.groupBox_scan_keithley)
        self.tabWidget_scan_keithley.setGeometry(QtCore.QRect(10, 60, 161, 71))
        self.tabWidget_scan_keithley.setObjectName(_fromUtf8("tabWidget_scan_keithley"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.radioButton_mv_keithley = QtGui.QRadioButton(self.tab)
        self.radioButton_mv_keithley.setGeometry(QtCore.QRect(60, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_mv_keithley.setFont(font)
        self.radioButton_mv_keithley.setChecked(True)
        self.radioButton_mv_keithley.setObjectName(_fromUtf8("radioButton_mv_keithley"))
        self.radioButton_v_keithley = QtGui.QRadioButton(self.tab)
        self.radioButton_v_keithley.setGeometry(QtCore.QRect(110, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_v_keithley.setFont(font)
        self.radioButton_v_keithley.setObjectName(_fromUtf8("radioButton_v_keithley"))
        self.radioButton_uv_keithley = QtGui.QRadioButton(self.tab)
        self.radioButton_uv_keithley.setGeometry(QtCore.QRect(10, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_uv_keithley.setFont(font)
        self.radioButton_uv_keithley.setObjectName(_fromUtf8("radioButton_uv_keithley"))
        self.tabWidget_scan_keithley.addTab(self.tab, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.radioButton_na_keithley = QtGui.QRadioButton(self.tab_5)
        self.radioButton_na_keithley.setGeometry(QtCore.QRect(10, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_na_keithley.setFont(font)
        self.radioButton_na_keithley.setChecked(True)
        self.radioButton_na_keithley.setObjectName(_fromUtf8("radioButton_na_keithley"))
        self.radioButton_ua_keithley = QtGui.QRadioButton(self.tab_5)
        self.radioButton_ua_keithley.setGeometry(QtCore.QRect(70, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_ua_keithley.setFont(font)
        self.radioButton_ua_keithley.setObjectName(_fromUtf8("radioButton_ua_keithley"))
        self.radioButton_ma_keithley = QtGui.QRadioButton(self.tab_5)
        self.radioButton_ma_keithley.setGeometry(QtCore.QRect(130, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_ma_keithley.setFont(font)
        self.radioButton_ma_keithley.setObjectName(_fromUtf8("radioButton_ma_keithley"))
        self.tabWidget_scan_keithley.addTab(self.tab_5, _fromUtf8(""))
        self.label_yname_keithley_2 = QtGui.QLabel(self.groupBox_scan_keithley)
        self.label_yname_keithley_2.setGeometry(QtCore.QRect(10, 140, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_yname_keithley_2.setFont(font)
        self.label_yname_keithley_2.setObjectName(_fromUtf8("label_yname_keithley_2"))
        self.lineEdit_tstep_keithley = QtGui.QLineEdit(self.groupBox_scan_keithley)
        self.lineEdit_tstep_keithley.setGeometry(QtCore.QRect(10, 170, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_tstep_keithley.setFont(font)
        self.lineEdit_tstep_keithley.setObjectName(_fromUtf8("lineEdit_tstep_keithley"))
        self.label_yvalue_keithley = QtGui.QLabel(self.groupBox_scan_keithley)
        self.label_yvalue_keithley.setGeometry(QtCore.QRect(280, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_yvalue_keithley.setFont(font)
        self.label_yvalue_keithley.setText(_fromUtf8(""))
        self.label_yvalue_keithley.setObjectName(_fromUtf8("label_yvalue_keithley"))
        self.label_xvalue_keithley = QtGui.QLabel(self.groupBox_scan_keithley)
        self.label_xvalue_keithley.setGeometry(QtCore.QRect(280, 50, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_xvalue_keithley.setFont(font)
        self.label_xvalue_keithley.setText(_fromUtf8(""))
        self.label_xvalue_keithley.setObjectName(_fromUtf8("label_xvalue_keithley"))
        self.label_tname_keithley = QtGui.QLabel(self.groupBox_scan_keithley)
        self.label_tname_keithley.setGeometry(QtCore.QRect(220, 80, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_tname_keithley.setFont(font)
        self.label_tname_keithley.setObjectName(_fromUtf8("label_tname_keithley"))
        self.label_tvalue_keithley = QtGui.QLabel(self.groupBox_scan_keithley)
        self.label_tvalue_keithley.setGeometry(QtCore.QRect(280, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_tvalue_keithley.setFont(font)
        self.label_tvalue_keithley.setText(_fromUtf8(""))
        self.label_tvalue_keithley.setObjectName(_fromUtf8("label_tvalue_keithley"))
        self.label_tunit_keithley = QtGui.QLabel(self.groupBox_scan_keithley)
        self.label_tunit_keithley.setGeometry(QtCore.QRect(350, 80, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_tunit_keithley.setFont(font)
        self.label_tunit_keithley.setText(_fromUtf8(""))
        self.label_tunit_keithley.setObjectName(_fromUtf8("label_tunit_keithley"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_31 = QtGui.QWidget()
        self.tab_31.setObjectName(_fromUtf8("tab_31"))
        self.saveBox = QtGui.QGroupBox(self.tab_31)
        self.saveBox.setGeometry(QtCore.QRect(10, 270, 181, 271))
        self.saveBox.setObjectName(_fromUtf8("saveBox"))
        self.browseButton = QtGui.QPushButton(self.saveBox)
        self.browseButton.setGeometry(QtCore.QRect(10, 30, 71, 31))
        self.browseButton.setObjectName(_fromUtf8("browseButton"))
        self.fileTypeLable = QtGui.QLabel(self.saveBox)
        self.fileTypeLable.setGeometry(QtCore.QRect(10, 70, 71, 31))
        self.fileTypeLable.setObjectName(_fromUtf8("fileTypeLable"))
        self.csvRadio = QtGui.QRadioButton(self.saveBox)
        self.csvRadio.setGeometry(QtCore.QRect(90, 90, 51, 21))
        self.csvRadio.setObjectName(_fromUtf8("csvRadio"))
        self.txtRadio = QtGui.QRadioButton(self.saveBox)
        self.txtRadio.setGeometry(QtCore.QRect(90, 70, 51, 21))
        self.txtRadio.setObjectName(_fromUtf8("txtRadio"))
        self.directoryLable = QtGui.QLabel(self.saveBox)
        self.directoryLable.setGeometry(QtCore.QRect(10, 120, 81, 31))
        self.directoryLable.setObjectName(_fromUtf8("directoryLable"))
        self.directory = QtGui.QLineEdit(self.saveBox)
        self.directory.setGeometry(QtCore.QRect(10, 150, 161, 31))
        self.directory.setObjectName(_fromUtf8("directory"))
        self.saveButton = QtGui.QPushButton(self.saveBox)
        self.saveButton.setGeometry(QtCore.QRect(100, 30, 71, 31))
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.folderName = QtGui.QComboBox(self.saveBox)
        self.folderName.setGeometry(QtCore.QRect(10, 220, 161, 31))
        self.folderName.setObjectName(_fromUtf8("folderName"))
        self.folderNameLable = QtGui.QLabel(self.saveBox)
        self.folderNameLable.setGeometry(QtCore.QRect(10, 190, 111, 31))
        self.folderNameLable.setObjectName(_fromUtf8("folderNameLable"))
        self.fileBox = QtGui.QGroupBox(self.tab_31)
        self.fileBox.setGeometry(QtCore.QRect(10, 160, 311, 101))
        self.fileBox.setObjectName(_fromUtf8("fileBox"))
        self.defaultFile = QtGui.QRadioButton(self.fileBox)
        self.defaultFile.setGeometry(QtCore.QRect(10, 20, 131, 31))
        self.defaultFile.setObjectName(_fromUtf8("defaultFile"))
        self.customFile = QtGui.QRadioButton(self.fileBox)
        self.customFile.setGeometry(QtCore.QRect(10, 50, 81, 31))
        self.customFile.setObjectName(_fromUtf8("customFile"))
        self.file = QtGui.QLineEdit(self.fileBox)
        self.file.setGeometry(QtCore.QRect(90, 50, 211, 31))
        self.file.setObjectName(_fromUtf8("file"))
        self.output = QtGui.QTextEdit(self.tab_31)
        self.output.setGeometry(QtCore.QRect(10, 720, 311, 101))
        self.output.setObjectName(_fromUtf8("output"))
        self.outputLable = QtGui.QLabel(self.tab_31)
        self.outputLable.setGeometry(QtCore.QRect(10, 690, 61, 31))
        self.outputLable.setObjectName(_fromUtf8("outputLable"))
        self.errorLable = QtGui.QLabel(self.tab_31)
        self.errorLable.setGeometry(QtCore.QRect(10, 550, 51, 31))
        self.errorLable.setObjectName(_fromUtf8("errorLable"))
        self.error = QtGui.QTextEdit(self.tab_31)
        self.error.setGeometry(QtCore.QRect(10, 580, 311, 101))
        self.error.setObjectName(_fromUtf8("error"))
        self.groupBox_import_keithley_2 = QtGui.QGroupBox(self.tab_31)
        self.groupBox_import_keithley_2.setGeometry(QtCore.QRect(10, 10, 311, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_import_keithley_2.setFont(font)
        self.groupBox_import_keithley_2.setObjectName(_fromUtf8("groupBox_import_keithley_2"))
        self.lineEdit_directory_ay = QtGui.QLineEdit(self.groupBox_import_keithley_2)
        self.lineEdit_directory_ay.setGeometry(QtCore.QRect(20, 50, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_directory_ay.setFont(font)
        self.lineEdit_directory_ay.setObjectName(_fromUtf8("lineEdit_directory_ay"))
        self.lable_import_ay = QtGui.QLabel(self.groupBox_import_keithley_2)
        self.lable_import_ay.setGeometry(QtCore.QRect(20, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lable_import_ay.setFont(font)
        self.lable_import_ay.setObjectName(_fromUtf8("lable_import_ay"))
        self.pushButton_browse_ay = QtGui.QPushButton(self.groupBox_import_keithley_2)
        self.pushButton_browse_ay.setGeometry(QtCore.QRect(20, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_browse_ay.setFont(font)
        self.pushButton_browse_ay.setObjectName(_fromUtf8("pushButton_browse_ay"))
        self.pushButton_import_ay = QtGui.QPushButton(self.groupBox_import_keithley_2)
        self.pushButton_import_ay.setEnabled(False)
        self.pushButton_import_ay.setGeometry(QtCore.QRect(120, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_import_ay.setFont(font)
        self.pushButton_import_ay.setObjectName(_fromUtf8("pushButton_import_ay"))
        self.pushButton_copy_ay = QtGui.QPushButton(self.groupBox_import_keithley_2)
        self.pushButton_copy_ay.setEnabled(True)
        self.pushButton_copy_ay.setGeometry(QtCore.QRect(220, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_copy_ay.setFont(font)
        self.pushButton_copy_ay.setObjectName(_fromUtf8("pushButton_copy_ay"))
        self.groupBox = QtGui.QGroupBox(self.tab_31)
        self.groupBox.setGeometry(QtCore.QRect(330, 10, 761, 161))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.selectVisaLable0 = QtGui.QLabel(self.groupBox)
        self.selectVisaLable0.setGeometry(QtCore.QRect(100, 20, 161, 31))
        self.selectVisaLable0.setObjectName(_fromUtf8("selectVisaLable0"))
        self.selectVisa0 = QtGui.QComboBox(self.groupBox)
        self.selectVisa0.setGeometry(QtCore.QRect(260, 20, 371, 31))
        self.selectVisa0.setObjectName(_fromUtf8("selectVisa0"))
        self.visaLable0 = QtGui.QLabel(self.groupBox)
        self.visaLable0.setGeometry(QtCore.QRect(100, 50, 161, 31))
        self.visaLable0.setObjectName(_fromUtf8("visaLable0"))
        self.visa0 = QtGui.QLabel(self.groupBox)
        self.visa0.setGeometry(QtCore.QRect(260, 50, 491, 31))
        self.visa0.setText(_fromUtf8(""))
        self.visa0.setObjectName(_fromUtf8("visa0"))
        self.selectVisaLable1 = QtGui.QLabel(self.groupBox)
        self.selectVisaLable1.setGeometry(QtCore.QRect(100, 90, 161, 31))
        self.selectVisaLable1.setObjectName(_fromUtf8("selectVisaLable1"))
        self.selectVisa1 = QtGui.QComboBox(self.groupBox)
        self.selectVisa1.setGeometry(QtCore.QRect(260, 90, 371, 31))
        self.selectVisa1.setObjectName(_fromUtf8("selectVisa1"))
        self.visa1 = QtGui.QLabel(self.groupBox)
        self.visa1.setGeometry(QtCore.QRect(260, 120, 491, 31))
        self.visa1.setText(_fromUtf8(""))
        self.visa1.setObjectName(_fromUtf8("visa1"))
        self.visaLable1 = QtGui.QLabel(self.groupBox)
        self.visaLable1.setGeometry(QtCore.QRect(100, 120, 161, 31))
        self.visaLable1.setObjectName(_fromUtf8("visaLable1"))
        self.closeVisaButton0 = QtGui.QPushButton(self.groupBox)
        self.closeVisaButton0.setGeometry(QtCore.QRect(640, 20, 111, 31))
        self.closeVisaButton0.setObjectName(_fromUtf8("closeVisaButton0"))
        self.closeVisaButton1 = QtGui.QPushButton(self.groupBox)
        self.closeVisaButton1.setGeometry(QtCore.QRect(640, 90, 111, 31))
        self.closeVisaButton1.setObjectName(_fromUtf8("closeVisaButton1"))
        self.selectVisaButton = QtGui.QPushButton(self.groupBox)
        self.selectVisaButton.setGeometry(QtCore.QRect(10, 70, 81, 31))
        self.selectVisaButton.setObjectName(_fromUtf8("selectVisaButton"))
        self.updateVisaButton = QtGui.QPushButton(self.groupBox)
        self.updateVisaButton.setGeometry(QtCore.QRect(10, 30, 81, 31))
        self.updateVisaButton.setObjectName(_fromUtf8("updateVisaButton"))
        self.groupBox_scan_ay = QtGui.QGroupBox(self.tab_31)
        self.groupBox_scan_ay.setGeometry(QtCore.QRect(200, 270, 121, 271))
        self.groupBox_scan_ay.setObjectName(_fromUtf8("groupBox_scan_ay"))
        self.startButton = QtGui.QPushButton(self.groupBox_scan_ay)
        self.startButton.setGeometry(QtCore.QRect(10, 30, 101, 41))
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.stopButton = QtGui.QPushButton(self.groupBox_scan_ay)
        self.stopButton.setGeometry(QtCore.QRect(20, 80, 81, 41))
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.timeStepValueLable = QtGui.QLabel(self.groupBox_scan_ay)
        self.timeStepValueLable.setGeometry(QtCore.QRect(20, 190, 81, 31))
        self.timeStepValueLable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.timeStepValueLable.setObjectName(_fromUtf8("timeStepValueLable"))
        self.timeStepValue = QtGui.QLineEdit(self.groupBox_scan_ay)
        self.timeStepValue.setGeometry(QtCore.QRect(10, 220, 101, 31))
        self.timeStepValue.setObjectName(_fromUtf8("timeStepValue"))
        self.tabWidget_plot_ay = QtGui.QTabWidget(self.tab_31)
        self.tabWidget_plot_ay.setGeometry(QtCore.QRect(330, 180, 761, 641))
        self.tabWidget_plot_ay.setObjectName(_fromUtf8("tabWidget_plot_ay"))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.curvewidget_importPlot_ay = CurveWidget(self.tab_11)
        self.curvewidget_importPlot_ay.setGeometry(QtCore.QRect(0, 0, 751, 601))
        self.curvewidget_importPlot_ay.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_importPlot_ay.setObjectName(_fromUtf8("curvewidget_importPlot_ay"))
        self.tabWidget_plot_ay.addTab(self.tab_11, _fromUtf8(""))
        self.tab_21 = QtGui.QWidget()
        self.tab_21.setObjectName(_fromUtf8("tab_21"))
        self.curvewidget_scanPlot_ay = CurveWidget(self.tab_21)
        self.curvewidget_scanPlot_ay.setGeometry(QtCore.QRect(0, 0, 751, 601))
        self.curvewidget_scanPlot_ay.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_scanPlot_ay.setObjectName(_fromUtf8("curvewidget_scanPlot_ay"))
        self.tabWidget_plot_ay.addTab(self.tab_21, _fromUtf8(""))
        self.tabWidget.addTab(self.tab_31, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_plot_keithely.setCurrentIndex(0)
        self.tabWidget_scan_keithley.setCurrentIndex(0)
        self.tabWidget_plot_ay.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_parameter.setTitle(_translate("MainWindow", "Parameter", None))
        self.label_starting_value.setText(_translate("MainWindow", "Starting Value:", None))
        self.lineEdit_start.setText(_translate("MainWindow", "0", None))
        self.pushButton_plot.setText(_translate("MainWindow", "Plot", None))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear", None))
        self.label_2.setText(_translate("MainWindow", "Steps, Repeat, Peaks:", None))
        self.groupBox_save_general.setTitle(_translate("MainWindow", "Save", None))
        self.label_4.setText(_translate("MainWindow", "Array Name:", None))
        self.pushButton_save.setText(_translate("MainWindow", "Save", None))
        self.label_6.setText(_translate("MainWindow", "Directory:", None))
        self.pushButton_browse_save.setText(_translate("MainWindow", "Browse", None))
        self.label_10.setText(_translate("MainWindow", "User Name:", None))
        self.groupBox_plot.setTitle(_translate("MainWindow", "Plot", None))
        self.groupBox_condition_general.setTitle(_translate("MainWindow", "Condition", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Array Builder", None))
        self.groupBox_import_keithley.setTitle(_translate("MainWindow", "Import", None))
        self.label_7.setText(_translate("MainWindow", "Array Import:", None))
        self.pushButton_browse_keithley.setText(_translate("MainWindow", "Browse", None))
        self.pushButton_import_keithley.setText(_translate("MainWindow", "Import", None))
        self.pushButton_copy_keithley.setText(_translate("MainWindow", "copy", None))
        self.tabWidget_plot_keithely.setTabText(self.tabWidget_plot_keithely.indexOf(self.tab_3), _translate("MainWindow", "Import Plot", None))
        self.tabWidget_plot_keithely.setTabText(self.tabWidget_plot_keithely.indexOf(self.tab_4), _translate("MainWindow", "Scan Plot", None))
        self.tabWidget_plot_keithely.setTabText(self.tabWidget_plot_keithely.indexOf(self.tab_6), _translate("MainWindow", "Analysis", None))
        self.groupBox_save_keithley.setTitle(_translate("MainWindow", "Save", None))
        self.label_21.setText(_translate("MainWindow", "Google Drive directory:", None))
        self.lineEdit_GoogleDrive_keithley.setText(_translate("MainWindow", "C:\\Google Drive\\03 User Accounts", None))
        self.label_22.setText(_translate("MainWindow", "Pick up a name folder", None))
        self.comboBox_Name_Folder_keithley.setItemText(0, _translate("MainWindow", "None", None))
        self.comboBox_Name_Folder_keithley.setItemText(1, _translate("MainWindow", "Horimbere", None))
        self.comboBox_Name_Folder_keithley.setItemText(2, _translate("MainWindow", "Sell", None))
        self.comboBox_Name_Folder_keithley.setItemText(3, _translate("MainWindow", "Snyder", None))
        self.comboBox_Name_Folder_keithley.setItemText(4, _translate("MainWindow", "Tran", None))
        self.comboBox_Name_Folder_keithley.setItemText(5, _translate("MainWindow", "Vannucci", None))
        self.comboBox_Name_Folder_keithley.setItemText(6, _translate("MainWindow", "Wang", None))
        self.comboBox_Name_Folder_keithley.setItemText(7, _translate("MainWindow", "Williams", None))
        self.pushButton_Select_Directory_keithley.setText(_translate("MainWindow", "Select", None))
        self.groupBox_File_Type_keithley.setTitle(_translate("MainWindow", "File type", None))
        self.radioButton_csv_keithley.setText(_translate("MainWindow", "csv", None))
        self.radioButton_txt_keithley.setText(_translate("MainWindow", "txt", None))
        self.groupBox_Filename_keithley.setTitle(_translate("MainWindow", "File name", None))
        self.radioButton_Timename_keithley.setText(_translate("MainWindow", "Date and time", None))
        self.radioButton_Custom_Name_keithley.setText(_translate("MainWindow", "Custom", None))
        self.pushButton_Save_keithley.setText(_translate("MainWindow", "Save", None))
        self.pushButton_Open_keithley.setText(_translate("MainWindow", "Open", None))
        self.pushButton_browse_save_keithley.setText(_translate("MainWindow", "Browse", None))
        self.pushButton_check_keithley.setText(_translate("MainWindow", "Check", None))
        self.label_15.setText(_translate("MainWindow", "Condition:", None))
        self.label_32.setText(_translate("MainWindow", "Comment:", None))
        self.tabWidget_plot_keithely.setTabText(self.tabWidget_plot_keithely.indexOf(self.tab_7), _translate("MainWindow", "Save", None))
        self.groupBox_condition_keithley.setTitle(_translate("MainWindow", "Condition", None))
        self.groupBox_visa_keithley.setTitle(_translate("MainWindow", "Visa", None))
        self.label_chooseVisa.setText(_translate("MainWindow", "Choose VISA", None))
        self.pushButton_select_keithley.setText(_translate("MainWindow", "Select", None))
        self.pushButton_close_keithley.setText(_translate("MainWindow", "Close", None))
        self.label_8.setText(_translate("MainWindow", "VISA name:", None))
        self.lineEdit_visa_keithley.setText(_translate("MainWindow", "None", None))
        self.groupBox_scan_keithley.setTitle(_translate("MainWindow", "Scan", None))
        self.label.setText(_translate("MainWindow", "Source:", None))
        self.radioButton_voltage_keithley.setText(_translate("MainWindow", "Voltage", None))
        self.pushButton_scan_keithley.setText(_translate("MainWindow", "Scan", None))
        self.pushButton_stop_keithley.setText(_translate("MainWindow", "Stop", None))
        self.pushButton_clear_keithley.setText(_translate("MainWindow", "Clear", None))
        self.label_xname_keithley.setText(_translate("MainWindow", "X-Value:", None))
        self.label_yname_keithley.setText(_translate("MainWindow", "Y-Value:", None))
        self.pushButton_pause_keithley.setText(_translate("MainWindow", "Pause", None))
        self.radioButton_mv_keithley.setText(_translate("MainWindow", "mV", None))
        self.radioButton_v_keithley.setText(_translate("MainWindow", "V", None))
        self.radioButton_uv_keithley.setText(_translate("MainWindow", "uV", None))
        self.tabWidget_scan_keithley.setTabText(self.tabWidget_scan_keithley.indexOf(self.tab), _translate("MainWindow", "V unit", None))
        self.radioButton_na_keithley.setText(_translate("MainWindow", "nA", None))
        self.radioButton_ua_keithley.setText(_translate("MainWindow", "uA", None))
        self.radioButton_ma_keithley.setText(_translate("MainWindow", "mA", None))
        self.tabWidget_scan_keithley.setTabText(self.tabWidget_scan_keithley.indexOf(self.tab_5), _translate("MainWindow", "C unit", None))
        self.label_yname_keithley_2.setText(_translate("MainWindow", "Time Step(sec):", None))
        self.lineEdit_tstep_keithley.setText(_translate("MainWindow", "0.2", None))
        self.label_tname_keithley.setText(_translate("MainWindow", "Time:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Keithley", None))
        self.saveBox.setTitle(_translate("MainWindow", "Save", None))
        self.browseButton.setText(_translate("MainWindow", "Browse", None))
        self.fileTypeLable.setText(_translate("MainWindow", "File Type:", None))
        self.csvRadio.setText(_translate("MainWindow", "csv", None))
        self.txtRadio.setText(_translate("MainWindow", "txt", None))
        self.directoryLable.setText(_translate("MainWindow", "Directory:", None))
        self.saveButton.setText(_translate("MainWindow", "Save", None))
        self.folderNameLable.setText(_translate("MainWindow", "Folder Name:", None))
        self.fileBox.setTitle(_translate("MainWindow", "File Name", None))
        self.defaultFile.setText(_translate("MainWindow", "Date and Time", None))
        self.customFile.setText(_translate("MainWindow", "Custum", None))
        self.outputLable.setText(_translate("MainWindow", "Output:", None))
        self.errorLable.setText(_translate("MainWindow", "Error:", None))
        self.groupBox_import_keithley_2.setTitle(_translate("MainWindow", "Import", None))
        self.lable_import_ay.setText(_translate("MainWindow", "Array Import:", None))
        self.pushButton_browse_ay.setText(_translate("MainWindow", "Browse", None))
        self.pushButton_import_ay.setText(_translate("MainWindow", "Import", None))
        self.pushButton_copy_ay.setText(_translate("MainWindow", "Copy", None))
        self.groupBox.setTitle(_translate("MainWindow", "Select Device", None))
        self.selectVisaLable0.setText(_translate("MainWindow", "Select Visa (Current):", None))
        self.visaLable0.setText(_translate("MainWindow", "Current Visa (Curent):", None))
        self.selectVisaLable1.setText(_translate("MainWindow", "Select Visa (Voltage):", None))
        self.visaLable1.setText(_translate("MainWindow", "Curent Visa (Voltage):", None))
        self.closeVisaButton0.setText(_translate("MainWindow", "Close Visa (I)", None))
        self.closeVisaButton1.setText(_translate("MainWindow", "Close Visa (V)", None))
        self.selectVisaButton.setText(_translate("MainWindow", "Select", None))
        self.updateVisaButton.setText(_translate("MainWindow", "Update", None))
        self.groupBox_scan_ay.setTitle(_translate("MainWindow", "Scan", None))
        self.startButton.setText(_translate("MainWindow", "Start", None))
        self.stopButton.setText(_translate("MainWindow", "Stop", None))
        self.timeStepValueLable.setText(_translate("MainWindow", "Time Step", None))
        self.tabWidget_plot_ay.setTabText(self.tabWidget_plot_ay.indexOf(self.tab_11), _translate("MainWindow", "Imported Plot", None))
        self.tabWidget_plot_ay.setTabText(self.tabWidget_plot_ay.indexOf(self.tab_21), _translate("MainWindow", "Scan Plot", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_31), _translate("MainWindow", "Agilent / Yokogawa", None))

from matplotlibwidget import MatplotlibWidget
from guiqwt.plot import CurveWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

